package com.puck.intelrecom.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BsAsset {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.asset_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String assetId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.asset_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String assetType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.asset_amount
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private BigDecimal assetAmount;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String customerBelong;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bs_asset.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Date updateTime;

	private int integral = 0;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.id
	 *
	 * @return the value of bs_asset.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.id
	 *
	 * @param id the value for bs_asset.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.asset_id
	 *
	 * @return the value of bs_asset.asset_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getAssetId() {
		return assetId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.asset_id
	 *
	 * @param assetId the value for bs_asset.asset_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setAssetId(String assetId) {
		this.assetId = assetId == null ? null : assetId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.asset_type
	 *
	 * @return the value of bs_asset.asset_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getAssetType() {
		return assetType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.asset_type
	 *
	 * @param assetType the value for bs_asset.asset_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setAssetType(String assetType) {
		this.assetType = assetType == null ? null : assetType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.asset_amount
	 *
	 * @return the value of bs_asset.asset_amount
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public BigDecimal getAssetAmount() {
		return assetAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.asset_amount
	 *
	 * @param assetAmount the value for bs_asset.asset_amount
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setAssetAmount(BigDecimal assetAmount) {
		this.assetAmount = assetAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.customer_belong
	 *
	 * @return the value of bs_asset.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCustomerBelong() {
		return customerBelong;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.customer_belong
	 *
	 * @param customerBelong the value for bs_asset.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCustomerBelong(String customerBelong) {
		this.customerBelong = customerBelong == null ? null : customerBelong.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.status
	 *
	 * @return the value of bs_asset.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.status
	 *
	 * @param status the value for bs_asset.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.create_time
	 *
	 * @return the value of bs_asset.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.create_time
	 *
	 * @param createTime the value for bs_asset.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bs_asset.update_time
	 *
	 * @return the value of bs_asset.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bs_asset.update_time
	 *
	 * @param updateTime the value for bs_asset.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getIntegral() {
		return integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}
}