package com.puck.intelrecom.domain;

import java.util.Date;
import java.util.List;

public class BsCustomer {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.customer_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String customerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.customer_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String customerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.customer_short_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String customerShortName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.industry
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String industry;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.company_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String companyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.company_scale
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String companyScale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.create_date
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.org_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String orgBelong;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_customer.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	private Date updateTime;

	private List<BsAsset> assets;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.id
	 *
	 * @return the value of bs_customer.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.id
	 *
	 * @param id
	 *            the value for bs_customer.id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.customer_id
	 *
	 * @return the value of bs_customer.customer_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.customer_id
	 *
	 * @param customerId
	 *            the value for bs_customer.customer_id
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.customer_name
	 *
	 * @return the value of bs_customer.customer_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.customer_name
	 *
	 * @param customerName
	 *            the value for bs_customer.customer_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName == null ? null : customerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.customer_short_name
	 *
	 * @return the value of bs_customer.customer_short_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCustomerShortName() {
		return customerShortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.customer_short_name
	 *
	 * @param customerShortName
	 *            the value for bs_customer.customer_short_name
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCustomerShortName(String customerShortName) {
		this.customerShortName = customerShortName == null ? null : customerShortName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.industry
	 *
	 * @return the value of bs_customer.industry
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.industry
	 *
	 * @param industry
	 *            the value for bs_customer.industry
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setIndustry(String industry) {
		this.industry = industry == null ? null : industry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.company_type
	 *
	 * @return the value of bs_customer.company_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCompanyType() {
		return companyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.company_type
	 *
	 * @param companyType
	 *            the value for bs_customer.company_type
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCompanyType(String companyType) {
		this.companyType = companyType == null ? null : companyType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.company_scale
	 *
	 * @return the value of bs_customer.company_scale
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getCompanyScale() {
		return companyScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.company_scale
	 *
	 * @param companyScale
	 *            the value for bs_customer.company_scale
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCompanyScale(String companyScale) {
		this.companyScale = companyScale == null ? null : companyScale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.create_date
	 *
	 * @return the value of bs_customer.create_date
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.create_date
	 *
	 * @param createDate
	 *            the value for bs_customer.create_date
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.org_belong
	 *
	 * @return the value of bs_customer.org_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getOrgBelong() {
		return orgBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.org_belong
	 *
	 * @param orgBelong
	 *            the value for bs_customer.org_belong
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setOrgBelong(String orgBelong) {
		this.orgBelong = orgBelong == null ? null : orgBelong.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.status
	 *
	 * @return the value of bs_customer.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.status
	 *
	 * @param status
	 *            the value for bs_customer.status
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.create_time
	 *
	 * @return the value of bs_customer.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.create_time
	 *
	 * @param createTime
	 *            the value for bs_customer.create_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_customer.update_time
	 *
	 * @return the value of bs_customer.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_customer.update_time
	 *
	 * @param updateTime
	 *            the value for bs_customer.update_time
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public List<BsAsset> getAssets() {
		return assets;
	}

	public void setAssets(List<BsAsset> assets) {
		this.assets = assets;
	}
}