package com.puck.intelrecom.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BsProduct {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.product_id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String productId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.product_name
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String productName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.guarantee_type
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String guaranteeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.product_amount
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private BigDecimal productAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.period
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private Integer period;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.publish_org
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String publishOrg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String customerBelong;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.status
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.create_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_product.update_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	private Date updateTime;

	private int integral = 0;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.id
	 *
	 * @return the value of bs_product.id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.id
	 *
	 * @param id
	 *            the value for bs_product.id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.product_id
	 *
	 * @return the value of bs_product.product_id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.product_id
	 *
	 * @param productId
	 *            the value for bs_product.product_id
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setProductId(String productId) {
		this.productId = productId == null ? null : productId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.product_name
	 *
	 * @return the value of bs_product.product_name
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.product_name
	 *
	 * @param productName
	 *            the value for bs_product.product_name
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.guarantee_type
	 *
	 * @return the value of bs_product.guarantee_type
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getGuaranteeType() {
		return guaranteeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.guarantee_type
	 *
	 * @param guaranteeType
	 *            the value for bs_product.guarantee_type
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setGuaranteeType(String guaranteeType) {
		this.guaranteeType = guaranteeType == null ? null : guaranteeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.product_amount
	 *
	 * @return the value of bs_product.product_amount
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public BigDecimal getProductAmount() {
		return productAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.product_amount
	 *
	 * @param productAmount
	 *            the value for bs_product.product_amount
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setProductAmount(BigDecimal productAmount) {
		this.productAmount = productAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.period
	 *
	 * @return the value of bs_product.period
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.period
	 *
	 * @param period
	 *            the value for bs_product.period
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.publish_org
	 *
	 * @return the value of bs_product.publish_org
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getPublishOrg() {
		return publishOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.publish_org
	 *
	 * @param publishOrg
	 *            the value for bs_product.publish_org
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setPublishOrg(String publishOrg) {
		this.publishOrg = publishOrg == null ? null : publishOrg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.customer_belong
	 *
	 * @return the value of bs_product.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getCustomerBelong() {
		return customerBelong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.customer_belong
	 *
	 * @param customerBelong
	 *            the value for bs_product.customer_belong
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setCustomerBelong(String customerBelong) {
		this.customerBelong = customerBelong == null ? null : customerBelong.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.status
	 *
	 * @return the value of bs_product.status
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.status
	 *
	 * @param status
	 *            the value for bs_product.status
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.create_time
	 *
	 * @return the value of bs_product.create_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.create_time
	 *
	 * @param createTime
	 *            the value for bs_product.create_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_product.update_time
	 *
	 * @return the value of bs_product.update_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_product.update_time
	 *
	 * @param updateTime
	 *            the value for bs_product.update_time
	 *
	 * @mbggenerated Tue Oct 25 16:39:26 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getIntegral() {
		return integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}

}