package com.puck.intelrecom.domain;

import java.math.BigDecimal;
import java.util.Date;

public class RuDilatationType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private Integer dilatationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private String dilatationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.point_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private String pointType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.point_value
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private String pointValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.dilatation_scale
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private BigDecimal dilatationScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_dilatation_type.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.dilatation_id
     *
     * @return the value of ru_dilatation_type.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public Integer getDilatationId() {
        return dilatationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.dilatation_id
     *
     * @param dilatationId the value for ru_dilatation_type.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setDilatationId(Integer dilatationId) {
        this.dilatationId = dilatationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.dilatation_type
     *
     * @return the value of ru_dilatation_type.dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public String getDilatationType() {
        return dilatationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.dilatation_type
     *
     * @param dilatationType the value for ru_dilatation_type.dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setDilatationType(String dilatationType) {
        this.dilatationType = dilatationType == null ? null : dilatationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.point_type
     *
     * @return the value of ru_dilatation_type.point_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.point_type
     *
     * @param pointType the value for ru_dilatation_type.point_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.point_value
     *
     * @return the value of ru_dilatation_type.point_value
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public String getPointValue() {
        return pointValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.point_value
     *
     * @param pointValue the value for ru_dilatation_type.point_value
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setPointValue(String pointValue) {
        this.pointValue = pointValue == null ? null : pointValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.dilatation_scale
     *
     * @return the value of ru_dilatation_type.dilatation_scale
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public BigDecimal getDilatationScale() {
        return dilatationScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.dilatation_scale
     *
     * @param dilatationScale the value for ru_dilatation_type.dilatation_scale
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setDilatationScale(BigDecimal dilatationScale) {
        this.dilatationScale = dilatationScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.status
     *
     * @return the value of ru_dilatation_type.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.status
     *
     * @param status the value for ru_dilatation_type.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_dilatation_type.create_time
     *
     * @return the value of ru_dilatation_type.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_dilatation_type.create_time
     *
     * @param createTime the value for ru_dilatation_type.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}