package com.puck.intelrecom.domain;

import java.util.Date;

public class RuRefRules extends RuRefRulesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_ref_rules.weight
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_ref_rules.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private Integer dilatationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_ref_rules.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ru_ref_rules.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_ref_rules.weight
     *
     * @return the value of ru_ref_rules.weight
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_ref_rules.weight
     *
     * @param weight the value for ru_ref_rules.weight
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_ref_rules.dilatation_id
     *
     * @return the value of ru_ref_rules.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public Integer getDilatationId() {
        return dilatationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_ref_rules.dilatation_id
     *
     * @param dilatationId the value for ru_ref_rules.dilatation_id
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setDilatationId(Integer dilatationId) {
        this.dilatationId = dilatationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_ref_rules.status
     *
     * @return the value of ru_ref_rules.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_ref_rules.status
     *
     * @param status the value for ru_ref_rules.status
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ru_ref_rules.create_time
     *
     * @return the value of ru_ref_rules.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ru_ref_rules.create_time
     *
     * @param createTime the value for ru_ref_rules.create_time
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}