package com.puck.intelrecom.mapper;

import java.util.List;

import com.puck.intelrecom.domain.BsAsset;

public interface BsAssetMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int insert(BsAsset record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int insertSelective(BsAsset record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	BsAsset selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int updateByPrimaryKeySelective(BsAsset record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bs_asset
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int updateByPrimaryKey(BsAsset record);

	/**
	 * 根据资产编号查询资产
	 * @param assetId
	 * @return
	 */
	public BsAsset selectBsAssetByAssetId(String assetId);

	/**
	 * 查询所有资产
	 * @return
	 */
	public List<BsAsset> selectAllAssets();
}