package com.puck.intelrecom.mapper;

import com.puck.intelrecom.domain.BsCustomer;

public interface BsCustomerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int insert(BsCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int insertSelective(BsCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	BsCustomer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int updateByPrimaryKeySelective(BsCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_customer
	 *
	 * @mbggenerated Tue Oct 25 14:53:01 CST 2016
	 */
	int updateByPrimaryKey(BsCustomer record);

	public BsCustomer selectCustomerWithAsset(String customerId);
}