package com.puck.intelrecom.mapper;

import com.puck.intelrecom.domain.BsDict;
import com.puck.intelrecom.domain.BsDictKey;

public interface BsDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    int deleteByPrimaryKey(BsDictKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    int insert(BsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    int insertSelective(BsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    BsDict selectByPrimaryKey(BsDictKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    int updateByPrimaryKeySelective(BsDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_dict
     *
     * @mbggenerated Tue Oct 25 14:53:01 CST 2016
     */
    int updateByPrimaryKey(BsDict record);
}