package com.puck.intelrecom.mapper;

import com.puck.intelrecom.domain.RuDilatationType;

public interface RuDilatationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int deleteByPrimaryKey(Integer dilatationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int insert(RuDilatationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int insertSelective(RuDilatationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    RuDilatationType selectByPrimaryKey(Integer dilatationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int updateByPrimaryKeySelective(RuDilatationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_type
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int updateByPrimaryKey(RuDilatationType record);
}