package com.puck.intelrecom.mapper;

import com.puck.intelrecom.domain.RuDilatationEnmu;

public interface RuDilatationEnmuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int insert(RuDilatationEnmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int insertSelective(RuDilatationEnmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    RuDilatationEnmu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int updateByPrimaryKeySelective(RuDilatationEnmu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ru_dilatation_enmu
     *
     * @mbggenerated Thu Oct 27 14:23:56 CST 2016
     */
    int updateByPrimaryKey(RuDilatationEnmu record);
}