package com.puck.intelrecom.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.puck.intelrecom.domain.RuRefRules;
import com.puck.intelrecom.domain.RuRefRulesKey;

public interface RuRefRulesMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	int deleteByPrimaryKey(RuRefRulesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	int insert(RuRefRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	int insertSelective(RuRefRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	RuRefRules selectByPrimaryKey(RuRefRulesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	int updateByPrimaryKeySelective(RuRefRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ru_ref_rules
	 *
	 * @mbggenerated Thu Oct 27 14:23:56 CST 2016
	 */
	int updateByPrimaryKey(RuRefRules record);

	/**
	 * 根据推荐源和被推荐对象查询数据
	 * @param recomdSource
	 * @param target
	 * @return
	 */
	public List<RuRefRules> selectEntityWeight(@Param("recomdSource") String recomdSource,
			@Param("target") String target);

	/**
	 * 根据推荐源、被推荐对象、推荐源属性查询记录
	 * @param recomdSource
	 * @param target
	 * @param recomdSourceCol
	 * @return
	 */
	public RuRefRules selectRuRefRuleWith3Keys(@Param("recomdSource") String recomdSource,
			@Param("target") String target, @Param("recomdSourceCol") String recomdSourceCol);
}